travis:
  secure:
    BINSTAR_TOKEN: ZkH54LxhuQb3jutoDHIoxOTDealAvwZ/59+Bdb79nd+fEHMQmKjpRdHOjDZr+OFBnH7l+/ZSosKAfo2HofNzk2PnIwxY937CGeQDMnCiiOPEanjPgutGsdTCdDzMVhj8QhduwC16dnUluS9WIRJe/g639oZ511Vb924f675IV9Co8gwUJAm6yZpgfMSMqcveaYR/YAqucHCfBRmd3AKNyQeUSWg8Ozy/l1pSRxBfLFMHUth0ZFj/gXXW62SdZdzuKlbG49bvyowKHv6xkvGO5SlMKf93g00qvzEop9fWfvTe1Pwtr5pFoBgVQSU5cGprHVeTXOOIeZaoWDPYL9O8QnSWE2xEfsL3GiKAG8g4XQ6X/eJOnSTl/zLgta33ZTp5BaSO2CNIhQv80ZToCUMPDPnPQ73eOwvfSazK3kJixRr9IhjJPFtuv+aN0n5ciohlESee3/NvycBlcw1iqTp5E53qUvpJaQztnqnXp6busIi6huUicnLc/0rAdd1sUB7WJqo9FRz47T9UQX9H3f/r7rQSrlod6S1eRAXiM822vlcinxLO6DKVCXvSpmDrYPUijA/LeR63f4a9/APfvx12Jdm+6mzxfaJYoz4S1bXYfMkaRe8QzvI6k/wBnigQcPPe/GTMF5KFYmI8rj5cXTOOCImID39IJkRGXuHdpJJ1cM4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
